class Cannon{
    constructor(x,y,width,height,angle){
        this.x=x;
        this.y=y;
        this.width=width;
        this.height=height;
        this.angle=angle;
    }
    display(){
        fill("gray");
        push();
        rectMode(CENTER);
        translate(this.x,this.y);
        rotate(this.angle)
        rect(-20,-30,this.width,this.height)
        pop();
        arc(this.x-35,this.y+85,140,200,PI,TWO_PI);
    }
}